---
language: node_js
node_js:
  - "7"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install
